[workspace]
members = [
  "hdfs-rs",
  "hdfs-tools",
  "gsasl-rs",
  "blitzwing",
]

[profile.release]
debug = 2
lto = true
opt-level = 3
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 1