brace_style = "SameLineWhere"
max_width = 100
merge_imports = true
newline_style = "Unix"
tab_spaces = 2
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true

ignore = [
  "hdfs-rs/proto",
  "blitzwing/proto"
]