// This file is generated by rust-protobuf 2.8.1. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `InterDatanodeProtocol.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_8_1;

#[derive(PartialEq,Clone,Default)]
pub struct InitReplicaRecoveryRequestProto {
    // message fields
    block: ::protobuf::SingularPtrField<super::hdfs::RecoveringBlockProto>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a InitReplicaRecoveryRequestProto {
    fn default() -> &'a InitReplicaRecoveryRequestProto {
        <InitReplicaRecoveryRequestProto as ::protobuf::Message>::default_instance()
    }
}

impl InitReplicaRecoveryRequestProto {
    pub fn new() -> InitReplicaRecoveryRequestProto {
        ::std::default::Default::default()
    }

    // required .hadoop.hdfs.RecoveringBlockProto block = 1;


    pub fn get_block(&self) -> &super::hdfs::RecoveringBlockProto {
        self.block.as_ref().unwrap_or_else(|| super::hdfs::RecoveringBlockProto::default_instance())
    }
    pub fn clear_block(&mut self) {
        self.block.clear();
    }

    pub fn has_block(&self) -> bool {
        self.block.is_some()
    }

    // Param is passed by value, moved
    pub fn set_block(&mut self, v: super::hdfs::RecoveringBlockProto) {
        self.block = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_block(&mut self) -> &mut super::hdfs::RecoveringBlockProto {
        if self.block.is_none() {
            self.block.set_default();
        }
        self.block.as_mut().unwrap()
    }

    // Take field
    pub fn take_block(&mut self) -> super::hdfs::RecoveringBlockProto {
        self.block.take().unwrap_or_else(|| super::hdfs::RecoveringBlockProto::new())
    }
}

impl ::protobuf::Message for InitReplicaRecoveryRequestProto {
    fn is_initialized(&self) -> bool {
        if self.block.is_none() {
            return false;
        }
        for v in &self.block {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.block)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.block.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.block.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> InitReplicaRecoveryRequestProto {
        InitReplicaRecoveryRequestProto::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::hdfs::RecoveringBlockProto>>(
                    "block",
                    |m: &InitReplicaRecoveryRequestProto| { &m.block },
                    |m: &mut InitReplicaRecoveryRequestProto| { &mut m.block },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<InitReplicaRecoveryRequestProto>(
                    "InitReplicaRecoveryRequestProto",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static InitReplicaRecoveryRequestProto {
        static mut instance: ::protobuf::lazy::Lazy<InitReplicaRecoveryRequestProto> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const InitReplicaRecoveryRequestProto,
        };
        unsafe {
            instance.get(InitReplicaRecoveryRequestProto::new)
        }
    }
}

impl ::protobuf::Clear for InitReplicaRecoveryRequestProto {
    fn clear(&mut self) {
        self.block.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for InitReplicaRecoveryRequestProto {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for InitReplicaRecoveryRequestProto {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct InitReplicaRecoveryResponseProto {
    // message fields
    replicaFound: ::std::option::Option<bool>,
    state: ::std::option::Option<super::hdfs::ReplicaStateProto>,
    block: ::protobuf::SingularPtrField<super::hdfs::BlockProto>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a InitReplicaRecoveryResponseProto {
    fn default() -> &'a InitReplicaRecoveryResponseProto {
        <InitReplicaRecoveryResponseProto as ::protobuf::Message>::default_instance()
    }
}

impl InitReplicaRecoveryResponseProto {
    pub fn new() -> InitReplicaRecoveryResponseProto {
        ::std::default::Default::default()
    }

    // required bool replicaFound = 1;


    pub fn get_replicaFound(&self) -> bool {
        self.replicaFound.unwrap_or(false)
    }
    pub fn clear_replicaFound(&mut self) {
        self.replicaFound = ::std::option::Option::None;
    }

    pub fn has_replicaFound(&self) -> bool {
        self.replicaFound.is_some()
    }

    // Param is passed by value, moved
    pub fn set_replicaFound(&mut self, v: bool) {
        self.replicaFound = ::std::option::Option::Some(v);
    }

    // optional .hadoop.hdfs.ReplicaStateProto state = 2;


    pub fn get_state(&self) -> super::hdfs::ReplicaStateProto {
        self.state.unwrap_or(super::hdfs::ReplicaStateProto::FINALIZED)
    }
    pub fn clear_state(&mut self) {
        self.state = ::std::option::Option::None;
    }

    pub fn has_state(&self) -> bool {
        self.state.is_some()
    }

    // Param is passed by value, moved
    pub fn set_state(&mut self, v: super::hdfs::ReplicaStateProto) {
        self.state = ::std::option::Option::Some(v);
    }

    // optional .hadoop.hdfs.BlockProto block = 3;


    pub fn get_block(&self) -> &super::hdfs::BlockProto {
        self.block.as_ref().unwrap_or_else(|| super::hdfs::BlockProto::default_instance())
    }
    pub fn clear_block(&mut self) {
        self.block.clear();
    }

    pub fn has_block(&self) -> bool {
        self.block.is_some()
    }

    // Param is passed by value, moved
    pub fn set_block(&mut self, v: super::hdfs::BlockProto) {
        self.block = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_block(&mut self) -> &mut super::hdfs::BlockProto {
        if self.block.is_none() {
            self.block.set_default();
        }
        self.block.as_mut().unwrap()
    }

    // Take field
    pub fn take_block(&mut self) -> super::hdfs::BlockProto {
        self.block.take().unwrap_or_else(|| super::hdfs::BlockProto::new())
    }
}

impl ::protobuf::Message for InitReplicaRecoveryResponseProto {
    fn is_initialized(&self) -> bool {
        if self.replicaFound.is_none() {
            return false;
        }
        for v in &self.block {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.replicaFound = ::std::option::Option::Some(tmp);
                },
                2 => {
                    ::protobuf::rt::read_proto2_enum_with_unknown_fields_into(wire_type, is, &mut self.state, 2, &mut self.unknown_fields)?
                },
                3 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.block)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(v) = self.replicaFound {
            my_size += 2;
        }
        if let Some(v) = self.state {
            my_size += ::protobuf::rt::enum_size(2, v);
        }
        if let Some(ref v) = self.block.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(v) = self.replicaFound {
            os.write_bool(1, v)?;
        }
        if let Some(v) = self.state {
            os.write_enum(2, v.value())?;
        }
        if let Some(ref v) = self.block.as_ref() {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> InitReplicaRecoveryResponseProto {
        InitReplicaRecoveryResponseProto::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                    "replicaFound",
                    |m: &InitReplicaRecoveryResponseProto| { &m.replicaFound },
                    |m: &mut InitReplicaRecoveryResponseProto| { &mut m.replicaFound },
                ));
                fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeEnum<super::hdfs::ReplicaStateProto>>(
                    "state",
                    |m: &InitReplicaRecoveryResponseProto| { &m.state },
                    |m: &mut InitReplicaRecoveryResponseProto| { &mut m.state },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::hdfs::BlockProto>>(
                    "block",
                    |m: &InitReplicaRecoveryResponseProto| { &m.block },
                    |m: &mut InitReplicaRecoveryResponseProto| { &mut m.block },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<InitReplicaRecoveryResponseProto>(
                    "InitReplicaRecoveryResponseProto",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static InitReplicaRecoveryResponseProto {
        static mut instance: ::protobuf::lazy::Lazy<InitReplicaRecoveryResponseProto> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const InitReplicaRecoveryResponseProto,
        };
        unsafe {
            instance.get(InitReplicaRecoveryResponseProto::new)
        }
    }
}

impl ::protobuf::Clear for InitReplicaRecoveryResponseProto {
    fn clear(&mut self) {
        self.replicaFound = ::std::option::Option::None;
        self.state = ::std::option::Option::None;
        self.block.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for InitReplicaRecoveryResponseProto {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for InitReplicaRecoveryResponseProto {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct UpdateReplicaUnderRecoveryRequestProto {
    // message fields
    block: ::protobuf::SingularPtrField<super::hdfs::ExtendedBlockProto>,
    recoveryId: ::std::option::Option<u64>,
    newLength: ::std::option::Option<u64>,
    newBlockId: ::std::option::Option<u64>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a UpdateReplicaUnderRecoveryRequestProto {
    fn default() -> &'a UpdateReplicaUnderRecoveryRequestProto {
        <UpdateReplicaUnderRecoveryRequestProto as ::protobuf::Message>::default_instance()
    }
}

impl UpdateReplicaUnderRecoveryRequestProto {
    pub fn new() -> UpdateReplicaUnderRecoveryRequestProto {
        ::std::default::Default::default()
    }

    // required .hadoop.hdfs.ExtendedBlockProto block = 1;


    pub fn get_block(&self) -> &super::hdfs::ExtendedBlockProto {
        self.block.as_ref().unwrap_or_else(|| super::hdfs::ExtendedBlockProto::default_instance())
    }
    pub fn clear_block(&mut self) {
        self.block.clear();
    }

    pub fn has_block(&self) -> bool {
        self.block.is_some()
    }

    // Param is passed by value, moved
    pub fn set_block(&mut self, v: super::hdfs::ExtendedBlockProto) {
        self.block = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_block(&mut self) -> &mut super::hdfs::ExtendedBlockProto {
        if self.block.is_none() {
            self.block.set_default();
        }
        self.block.as_mut().unwrap()
    }

    // Take field
    pub fn take_block(&mut self) -> super::hdfs::ExtendedBlockProto {
        self.block.take().unwrap_or_else(|| super::hdfs::ExtendedBlockProto::new())
    }

    // required uint64 recoveryId = 2;


    pub fn get_recoveryId(&self) -> u64 {
        self.recoveryId.unwrap_or(0)
    }
    pub fn clear_recoveryId(&mut self) {
        self.recoveryId = ::std::option::Option::None;
    }

    pub fn has_recoveryId(&self) -> bool {
        self.recoveryId.is_some()
    }

    // Param is passed by value, moved
    pub fn set_recoveryId(&mut self, v: u64) {
        self.recoveryId = ::std::option::Option::Some(v);
    }

    // required uint64 newLength = 3;


    pub fn get_newLength(&self) -> u64 {
        self.newLength.unwrap_or(0)
    }
    pub fn clear_newLength(&mut self) {
        self.newLength = ::std::option::Option::None;
    }

    pub fn has_newLength(&self) -> bool {
        self.newLength.is_some()
    }

    // Param is passed by value, moved
    pub fn set_newLength(&mut self, v: u64) {
        self.newLength = ::std::option::Option::Some(v);
    }

    // optional uint64 newBlockId = 4;


    pub fn get_newBlockId(&self) -> u64 {
        self.newBlockId.unwrap_or(0u64)
    }
    pub fn clear_newBlockId(&mut self) {
        self.newBlockId = ::std::option::Option::None;
    }

    pub fn has_newBlockId(&self) -> bool {
        self.newBlockId.is_some()
    }

    // Param is passed by value, moved
    pub fn set_newBlockId(&mut self, v: u64) {
        self.newBlockId = ::std::option::Option::Some(v);
    }
}

impl ::protobuf::Message for UpdateReplicaUnderRecoveryRequestProto {
    fn is_initialized(&self) -> bool {
        if self.block.is_none() {
            return false;
        }
        if self.recoveryId.is_none() {
            return false;
        }
        if self.newLength.is_none() {
            return false;
        }
        for v in &self.block {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.block)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.recoveryId = ::std::option::Option::Some(tmp);
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.newLength = ::std::option::Option::Some(tmp);
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.newBlockId = ::std::option::Option::Some(tmp);
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.block.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(v) = self.recoveryId {
            my_size += ::protobuf::rt::value_size(2, v, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(v) = self.newLength {
            my_size += ::protobuf::rt::value_size(3, v, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(v) = self.newBlockId {
            my_size += ::protobuf::rt::value_size(4, v, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.block.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(v) = self.recoveryId {
            os.write_uint64(2, v)?;
        }
        if let Some(v) = self.newLength {
            os.write_uint64(3, v)?;
        }
        if let Some(v) = self.newBlockId {
            os.write_uint64(4, v)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> UpdateReplicaUnderRecoveryRequestProto {
        UpdateReplicaUnderRecoveryRequestProto::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::hdfs::ExtendedBlockProto>>(
                    "block",
                    |m: &UpdateReplicaUnderRecoveryRequestProto| { &m.block },
                    |m: &mut UpdateReplicaUnderRecoveryRequestProto| { &mut m.block },
                ));
                fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "recoveryId",
                    |m: &UpdateReplicaUnderRecoveryRequestProto| { &m.recoveryId },
                    |m: &mut UpdateReplicaUnderRecoveryRequestProto| { &mut m.recoveryId },
                ));
                fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "newLength",
                    |m: &UpdateReplicaUnderRecoveryRequestProto| { &m.newLength },
                    |m: &mut UpdateReplicaUnderRecoveryRequestProto| { &mut m.newLength },
                ));
                fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "newBlockId",
                    |m: &UpdateReplicaUnderRecoveryRequestProto| { &m.newBlockId },
                    |m: &mut UpdateReplicaUnderRecoveryRequestProto| { &mut m.newBlockId },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<UpdateReplicaUnderRecoveryRequestProto>(
                    "UpdateReplicaUnderRecoveryRequestProto",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static UpdateReplicaUnderRecoveryRequestProto {
        static mut instance: ::protobuf::lazy::Lazy<UpdateReplicaUnderRecoveryRequestProto> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const UpdateReplicaUnderRecoveryRequestProto,
        };
        unsafe {
            instance.get(UpdateReplicaUnderRecoveryRequestProto::new)
        }
    }
}

impl ::protobuf::Clear for UpdateReplicaUnderRecoveryRequestProto {
    fn clear(&mut self) {
        self.block.clear();
        self.recoveryId = ::std::option::Option::None;
        self.newLength = ::std::option::Option::None;
        self.newBlockId = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for UpdateReplicaUnderRecoveryRequestProto {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for UpdateReplicaUnderRecoveryRequestProto {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct UpdateReplicaUnderRecoveryResponseProto {
    // message fields
    storageUuid: ::protobuf::SingularField<::std::string::String>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a UpdateReplicaUnderRecoveryResponseProto {
    fn default() -> &'a UpdateReplicaUnderRecoveryResponseProto {
        <UpdateReplicaUnderRecoveryResponseProto as ::protobuf::Message>::default_instance()
    }
}

impl UpdateReplicaUnderRecoveryResponseProto {
    pub fn new() -> UpdateReplicaUnderRecoveryResponseProto {
        ::std::default::Default::default()
    }

    // optional string storageUuid = 1;


    pub fn get_storageUuid(&self) -> &str {
        match self.storageUuid.as_ref() {
            Some(v) => &v,
            None => "",
        }
    }
    pub fn clear_storageUuid(&mut self) {
        self.storageUuid.clear();
    }

    pub fn has_storageUuid(&self) -> bool {
        self.storageUuid.is_some()
    }

    // Param is passed by value, moved
    pub fn set_storageUuid(&mut self, v: ::std::string::String) {
        self.storageUuid = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_storageUuid(&mut self) -> &mut ::std::string::String {
        if self.storageUuid.is_none() {
            self.storageUuid.set_default();
        }
        self.storageUuid.as_mut().unwrap()
    }

    // Take field
    pub fn take_storageUuid(&mut self) -> ::std::string::String {
        self.storageUuid.take().unwrap_or_else(|| ::std::string::String::new())
    }
}

impl ::protobuf::Message for UpdateReplicaUnderRecoveryResponseProto {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_string_into(wire_type, is, &mut self.storageUuid)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.storageUuid.as_ref() {
            my_size += ::protobuf::rt::string_size(1, &v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.storageUuid.as_ref() {
            os.write_string(1, &v)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> UpdateReplicaUnderRecoveryResponseProto {
        UpdateReplicaUnderRecoveryResponseProto::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "storageUuid",
                    |m: &UpdateReplicaUnderRecoveryResponseProto| { &m.storageUuid },
                    |m: &mut UpdateReplicaUnderRecoveryResponseProto| { &mut m.storageUuid },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<UpdateReplicaUnderRecoveryResponseProto>(
                    "UpdateReplicaUnderRecoveryResponseProto",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static UpdateReplicaUnderRecoveryResponseProto {
        static mut instance: ::protobuf::lazy::Lazy<UpdateReplicaUnderRecoveryResponseProto> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const UpdateReplicaUnderRecoveryResponseProto,
        };
        unsafe {
            instance.get(UpdateReplicaUnderRecoveryResponseProto::new)
        }
    }
}

impl ::protobuf::Clear for UpdateReplicaUnderRecoveryResponseProto {
    fn clear(&mut self) {
        self.storageUuid.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for UpdateReplicaUnderRecoveryResponseProto {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for UpdateReplicaUnderRecoveryResponseProto {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1bInterDatanodeProtocol.proto\x12\x0bhadoop.hdfs\x1a\nhdfs.proto\"S\
    \n\x1fInitReplicaRecoveryRequestProto\x120\n\x05block\x18\x01\x20\x02(\
    \x0b2!.hadoop.hdfs.RecoveringBlockProto\"\x8f\x01\n\x20InitReplicaRecove\
    ryResponseProto\x12\x14\n\x0creplicaFound\x18\x01\x20\x02(\x08\x12-\n\
    \x05state\x18\x02\x20\x01(\x0e2\x1e.hadoop.hdfs.ReplicaStateProto\x12&\n\
    \x05block\x18\x03\x20\x01(\x0b2\x17.hadoop.hdfs.BlockProto\"\x96\x01\n&U\
    pdateReplicaUnderRecoveryRequestProto\x12.\n\x05block\x18\x01\x20\x02(\
    \x0b2\x1f.hadoop.hdfs.ExtendedBlockProto\x12\x12\n\nrecoveryId\x18\x02\
    \x20\x02(\x04\x12\x11\n\tnewLength\x18\x03\x20\x02(\x04\x12\x15\n\nnewBl\
    ockId\x18\x04\x20\x01(\x04:\x010\">\n'UpdateReplicaUnderRecoveryResponse\
    Proto\x12\x13\n\x0bstorageUuid\x18\x01\x20\x01(\t2\x9c\x02\n\x1cInterDat\
    anodeProtocolService\x12r\n\x13initReplicaRecovery\x12,.hadoop.hdfs.Init\
    ReplicaRecoveryRequestProto\x1a-.hadoop.hdfs.InitReplicaRecoveryResponse\
    Proto\x12\x87\x01\n\x1aupdateReplicaUnderRecovery\x123.hadoop.hdfs.Updat\
    eReplicaUnderRecoveryRequestProto\x1a4.hadoop.hdfs.UpdateReplicaUnderRec\
    overyResponseProtoBJ\n%org.apache.hadoop.hdfs.protocol.protoB\x1bInterDa\
    tanodeProtocolProtos\xa0\x01\x01\x88\x01\x01\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
